2025-05-09 13:34:34,368 ERROR: Exception on /queries/ [GET] [in /opt/sidney/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/routes/queries.py", line 144, in index
    return render_template('queries/index.html', title='Query Database')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/sidney/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/sidney/app/templates/queries/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/templates/layout.html", line 93, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/templates/queries/index.html", line 58, in block 'content'
    <a href="{{ url_for('queries.custom') }}" class="btn" style="background-color: #4A4A4A; color: white;">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'queries.custom'. Did you mean 'queries.index' instead?
2025-05-09 13:34:34,371 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /opt/sidney/app/errors.py:10]
2025-05-09 13:34:37,821 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:34:39,096 ERROR: Exception on /queries/ [GET] [in /opt/sidney/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/routes/queries.py", line 144, in index
    return render_template('queries/index.html', title='Query Database')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/sidney/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/sidney/app/templates/queries/index.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/templates/layout.html", line 93, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/app/templates/queries/index.html", line 58, in block 'content'
    <a href="{{ url_for('queries.custom') }}" class="btn" style="background-color: #4A4A4A; color: white;">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sidney/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'queries.custom'. Did you mean 'queries.index' instead?
2025-05-09 13:34:39,097 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /opt/sidney/app/errors.py:10]
2025-05-09 13:36:33,445 INFO: Sidney starting up [in /opt/sidney/app/__init__.py:33]
2025-05-09 13:40:05,464 INFO: Sidney starting up [in /opt/sidney/app/__init__.py:33]
2025-05-09 13:40:09,287 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:45:57,451 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:46:04,054 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:46:16,321 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:46:19,171 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:46:20,015 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 13:46:20,786 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 14:58:00,428 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:02:22,583 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:10:23,942 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:10:25,639 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:10:27,112 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:10:34,526 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:10:34,576 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 15:12:08,090 INFO: Sidney starting up [in /opt/sidney/app/__init__.py:33]
2025-05-09 16:00:20,593 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
2025-05-09 16:02:41,461 ERROR: Error getting chart data: float() argument must be a string or a real number, not 'NoneType' [in /opt/sidney/app/routes/dashboard.py:204]
